{
 "title": "OPNsense Filter",
 "description": "A dashboard that visualizes filter logs from pfSense and OPNsense using regex parsing.",
 "tags": [
  "pfSense",
  "firewall",
  "network",
  "OPNsense"
 ],
 "time": { "from": "2025-10-12T20:57:26.207Z", "to": "2025-10-12T21:07:26.207Z" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource_loki", "label": "Data Source", "query": "loki" },
   {
    "name": "hostname",
    "label": "Instance",
    "query": {}
   },
   { "name": "regexipv4", "query": "${VAR_REGEXIPV4}" },
   { "name": "regexNonProto", "query": "${VAR_REGEXNONPROTO}" },
   { "name": "regexipv6", "query": "${VAR_REGEXIPV6}" },
   { "name": "regexcarp", "query": "${VAR_REGEXCARP}" },
   {
    "name": "interval",
    "label": "Timeline Interval",
    "query": "1s,2s,5s,10s,15s,30s,45s,1m,2m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "direction": "backward" }
   ]
  },
  {
   "title": "Source Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(source_country) (\n  count_over_time(\n    {host=~\".+\"} \n    | regexp `source_country=(?P<source_country>\\w+)` \n    | source_country != \"\"\n  [${__range}]\n  )\n)\n",
     "legendFormat": "{{source_country}}"
    }
   ]
  },
  {
   "title": "Destination Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(dest_country) (\n  count_over_time(\n    {host=~\".+\"} \n    | regexp `dest_country=(?P<dest_country>\\w+)` \n    | dest_country != \"\"\n  [${__range}]\n  )\n)\n",
     "legendFormat": "{{dest_country}}"
    }
   ]
  },
  {
   "title": "Source County",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=~\".+\"} | regexp `source_country=(?P<source_country>\\w+)` | line_format `{{.source_country}}`"
    }
   ]
  },
  {
   "title": "Destination County",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=~\".+\"} | regexp `dest_country=(?P<dest_country>\\w+)` | line_format `{{.dest_country}}`"
    }
   ]
  },
  {
   "title": "Action timeline",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(action) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 | action =~ `.+` [$__interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Packets by action",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 | action =~ `.+` [$__range]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Actions by rule",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(rule) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 | action =~ `.+`   [$__range]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Packets by interface",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(interface) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 [$__range]))",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Packets by IP version",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ipversion) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexNonProto` | ipversion =~ `\\d` [$__range]))",
     "legendFormat": "IPv{{ipversion}}"
    }
   ]
  },
  {
   "title": "Packets by protocol",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(protocol) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `(?i)$regexNonProto,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp)` | regexp `(?i)$regexNonProto,\\w+,\\w*,\\w+,\\w+,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp|carp)` | ipversion > 0 | label_format protocol=\"{{.protocol | ToLower }}\" [$__range]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Packets by IP version/protocol",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(protocol, ipversion) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `(?i)$regexNonProto,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp)` | regexp `(?i)$regexNonProto,\\w+,\\w*,\\w+,\\w+,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp|carp)` | ipversion > 0 | label_format protocol=\"{{.protocol | ToLower }}\" [$__range]))",
     "legendFormat": "IPv{{ipversion}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(srcip) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexipv4` | ipversion = `4` [$__range]))",
     "legendFormat": "{{srcip}}"
    },
    {
     "expr": "sum by(srcip) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexipv6` | ipversion = `6` [$__range]))",
     "legendFormat": "{{srcip}}"
    },
    {
     "expr": "sum by(srcip) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexcarp` | protocol = `carp` [$__range]))",
     "legendFormat": "{{srcip}}"
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dstip) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexipv4` | ipversion = `4` [$__range]))",
     "legendFormat": "{{dstip}}"
    },
    {
     "expr": "sum by(dstip) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexipv6` | ipversion = `6` [$__range]))",
     "legendFormat": "{{dstip}}"
    },
    {
     "expr": "sum by(dstip) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexcarp` | protocol = `carp` [$__range]))",
     "legendFormat": "{{dstip}}"
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dstport) (count_over_time({hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexipv4` | regexp `$regexipv6` | ipversion > 0 [$__range]))",
     "legendFormat": "{{ipversion}} {{dstport}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Filter Log",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexipv4` | ipversion = `4`  | label_format protocol=\"{{.protocol | ToLower }}\""
    },
    {
     "direction": "backward",
     "expr": "{hostname=~\"$hostname\", syslog_app=\"filterlog\"} | regexp `$regexipv6` | ipversion = `6` | label_format protocol=\"{{.protocol | ToLower }}\""
    }
   ]
  }
 ]
}